library(data.table)
exdata <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors=FALSE, dec=".")
exdata$Date<-as.Date(exdata$Date, "%d/%m/%Y")
exdata <- subset(exdata, exdata$Date=="2007-02-01" | exdata$Date=="2007-02-02")
attach(exdata)
time<- paste(Date, Time, sep=" ")
time<- strptime(time, "%Y-%m-%d %T")
png("plot2.png", width = 480, height = 480)
plot(time, Global_active_power, type = "n", xlab="", ylab="Global Active Power (kilowatts)")
lines(time, Global_active_power)
dev.off()