library(data.table)
exdata <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors=FALSE, dec=".")
exdata$Date<-as.Date(exdata$Date, "%d/%m/%Y")
exdata <- subset(exdata, exdata$Date=="2007-02-01" | exdata$Date=="2007-02-02")
attach(exdata)
png("plot1.png", width = 480, height = 480)
par(mar=c(4,4,4,4))
hist(as.numeric(Global_active_power), col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)", xaxp  = c(0, 6, 3))
dev.off()
