library(data.table)
exdata <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors=FALSE, dec=".")
exdata$Date<-as.Date(exdata$Date, "%d/%m/%Y")
exdata <- subset(exdata, exdata$Date=="2007-02-01" | exdata$Date=="2007-02-02")
attach(exdata)
time<- paste(Date, Time, sep=" ")
time<- strptime(time, "%Y-%m-%d %T")
png("plot3.png", width = 480, height = 480)
plot(time, Sub_metering_1, type = "n", xlab="", ylab="Energy sub metering")
lines(time, Sub_metering_1)
lines(time, Sub_metering_2, col="red")
lines(time, Sub_metering_3, col="blue")
legend("topright", col=c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1)
dev.off()